#!/usr/bin/env python3
"""Generate raw USSE field codecs from tools/usse_encodings.py.

The generator deliberately handles only bit layout. Semantic instruction
selection, register-bank meaning, scheduling, and validation against real Vita
programs remain handwritten in src/usse/usse.cpp.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from dataclasses import dataclass

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from usse_encodings import ENCODINGS  # noqa: E402


@dataclass(frozen=True)
class Field:
    name: str
    offset: int
    width: int


@dataclass(frozen=True)
class Encoding:
    name: str
    struct: str
    mask: int
    expected: int
    fields: tuple[Field, ...]
    constraints: tuple[dict, ...]


def parse_encoding(raw: dict) -> Encoding:
    bit = 64
    mask = 0
    expected = 0
    fields: list[Field] = []
    seen: set[str] = set()

    for token in raw["pattern"].split():
        if all(ch == "x" for ch in token):
            width = len(token)
            if width == 0 or width > bit:
                raise ValueError(f"{raw['name']}: invalid wildcard token {token!r}")
            bit -= width
            continue

        if all(ch in "01" for ch in token):
            width = len(token)
            if width == 0 or width > bit:
                raise ValueError(f"{raw['name']}: invalid fixed token {token!r}")
            bit -= width
            value = int(token, 2)
            token_mask = ((1 << width) - 1) << bit
            mask |= token_mask
            expected |= value << bit
            continue

        if ":" not in token:
            raise ValueError(f"{raw['name']}: invalid token {token!r}")
        name, width_text = token.split(":", 1)
        width = int(width_text, 10)
        if not name.isidentifier() or width <= 0 or width > bit:
            raise ValueError(f"{raw['name']}: invalid field {token!r}")
        if name in seen:
            raise ValueError(f"{raw['name']}: duplicate field {name}")
        seen.add(name)
        bit -= width
        fields.append(Field(name, bit, width))

    if bit != 0:
        raise ValueError(f"{raw['name']}: pattern describes {64 - bit} bits, expected 64")

    constraints = tuple(raw.get("constraints", ()))
    for constraint in constraints:
        if constraint.get("field") not in seen:
            raise ValueError(f"{raw['name']}: constraint references unknown field")
        if "min" not in constraint and "max" not in constraint:
            raise ValueError(f"{raw['name']}: empty constraint")

    return Encoding(
        name=raw["name"],
        struct=raw["struct"],
        mask=mask,
        expected=expected,
        fields=tuple(fields),
        constraints=constraints,
    )


def cpp_int_type(width: int) -> str:
    if width <= 8:
        return "uint8_t"
    if width <= 16:
        return "uint16_t"
    if width <= 32:
        return "uint32_t"
    return "uint64_t"


def camel(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def constraint_expression(prefix: str, constraint: dict) -> str:
    terms: list[str] = []
    field = f"{prefix}.{constraint['field']}"
    if "min" in constraint:
        terms.append(f"{field} >= {constraint['min']}")
    if "max" in constraint:
        terms.append(f"{field} <= {constraint['max']}")
    return " && ".join(terms)


def render(encodings: list[Encoding]) -> str:
    out: list[str] = []
    out.append("// Generated by tools/gen_usse_raw.py from tools/usse_encodings.py.")
    out.append("// Do not edit this file directly; edit the declarative spec and regenerate.")
    out.append("")
    out.append("namespace {")
    out.append("struct RawEncodingInfo {")
    out.append("    const char *name;")
    out.append("    uint64_t mask;")
    out.append("    uint64_t expected;")
    out.append("};")
    out.append("")
    for enc in encodings:
        prefix = camel(enc.name)
        out.append(f"constexpr uint64_t k{prefix}Mask = 0x{enc.mask:016x}ULL;")
        out.append(f"constexpr uint64_t k{prefix}Expected = 0x{enc.expected:016x}ULL;")
    out.append("")
    out.append("[[maybe_unused]] constexpr RawEncodingInfo kRawEncodings[] = {")
    for enc in encodings:
        prefix = camel(enc.name)
        out.append(f'    {{"{enc.name}", k{prefix}Mask, k{prefix}Expected}},')
    out.append("};")
    out.append("} // namespace")
    out.append("")

    for enc in encodings:
        prefix = camel(enc.name)
        out.append(f"bool decode_{enc.name}(uint64_t word, {enc.struct} *fields) {{")
        out.append(
            f"    if (!fields || (word & k{prefix}Mask) != k{prefix}Expected) return false;"
        )
        for fld in enc.fields:
            out.append(
                f"    fields->{fld.name} = field<{cpp_int_type(fld.width)}>(word, {fld.offset}, {fld.width});"
            )
        for constraint in enc.constraints:
            expr = constraint_expression("(*fields)", constraint)
            out.append(f"    if (!({expr})) return false;")
        out.append("    return true;")
        out.append("}")
        out.append("")

        out.append(f"bool encode_{enc.name}(const {enc.struct} &fields, uint64_t *word) {{")
        checks = [
            f"fits(static_cast<uint64_t>(fields.{fld.name}), {fld.width})"
            for fld in enc.fields
        ]
        if checks:
            out.append("    if (!word ||")
            for idx in range(0, len(checks), 3):
                chunk = checks[idx : idx + 3]
                suffix = " ||" if idx + 3 < len(checks) else ") return false;"
                out.append("        " + " || ".join(f"!{check}" for check in chunk) + suffix)
        else:
            out.append("    if (!word) return false;")
        for constraint in enc.constraints:
            expr = constraint_expression("fields", constraint)
            out.append(f"    if (!({expr})) return false;")
        out.append(f"    *word = k{prefix}Expected")
        for idx, fld in enumerate(enc.fields):
            suffix = ";" if idx == len(enc.fields) - 1 else ""
            out.append(f"        | bits(fields.{fld.name}, {fld.offset}, {fld.width}){suffix}")
        out.append("    return true;")
        out.append("}")
        out.append("")

    return "\n".join(out) + "\n"


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    default_output = root / "src" / "usse" / "usse_raw.generated.inc"

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path, default=default_output)
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    args = parser.parse_args()

    encodings = [parse_encoding(raw) for raw in ENCODINGS]
    generated = render(encodings)
    output = args.output

    if args.check:
        if not output.exists() or output.read_text() != generated:
            print(f"stale generated USSE codec file: {output}", file=sys.stderr)
            return 1
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
